
# Placeholder with simple test
structure(list(path = c("/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/021106_yossivassa.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/0Alice.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/11-17-06_Academy.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/1english-only.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/2005NISSE.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/2006_2007PhysicalEducationConceptMap.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/2006-07_Resource_Brochure.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/2007ShowcaseFilm_Package.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/22-ppa-3rd_e2snewsletter_jun06.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/42nd_street.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/5._.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/7-prikaz-slozeno.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/AccessToNationalSportsCentresPassportScheme.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/Adult-Sports.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/AfghanistanLiteracyDiscussionPaper.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/aReportOfTheSurgeonGeneral.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/ashaam2.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/BBVDlivepr.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/BBVDpr.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/BENEFITS_OF_EXERCISE_for_the_manual.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/billboard-021205.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/bio.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/Call-for-abstracts.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/ClaremontTrioBio0607.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/cme2i05.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/CommandGde.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/DanceFestOMAIPressReleaseFeb15_07.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/didges_brew_band_info.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/DOC-DHHS_Joint_Action_Plan_summary.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/ExercisePocketSliderText.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/exploring_dallas.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/exxonmobil_climate_change_backgrounder.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/FF06_press_9-7.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/Fitness_Myths.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/fitnessTerms.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/Global_Warming_Resolution_April_2001.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/gogirls.2003-10.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/GovernorsTaskForceReport.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/greenhouse.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/Groove_Yard.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/HandoutSportsInjuryPrevention.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/HSCPR10306.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/IntlChildrensFestRevisedRelease.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/lac_rfp_inner-cities.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/Landau-Pickford-Press-Rel.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/ledger091505.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/LOTRLeadRelease.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/Lotuspike-VBTD-Jenkins.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/MEDT6491.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/Meeting_the_Challenges.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/Memo_Ehrlich_1103.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/Midwestern_Rock_Garden.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/modelgeneralnotice.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/MRbio.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/Newsletter_20-1-3.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/parentarticle.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/record_voting.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/Reviews-GrooveYard.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/rkc_flyer.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/SAR_Dog_Avalanche_promo.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/SCE_3320.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/Shopping.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/sisters_pressrelease.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/small.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/small2.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/socy642_f02_milkie.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/SoundResources.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/spanish_place_namesA.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/spanish_place_namesB.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/sports_massage_and_recovery.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/srilanka.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/Summer_Math_Syllabus.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/survey_mathtch.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/syllabus.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/TeachingMathCameroon.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/The-Global-Warming-Response-Act.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/victim.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/website_course_descriptors06-07.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/Week3.txt",
                        "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ssdeepr/extdat/baseline/WPTC2006Season.txt"
), hash = c("96:1dTVKBhRebMHU8pwJigWo/rX4LqcuDKc/WDXQIIX8xv:x3B8pw1j0k/86a",
            "96:koJ37jheOX2F6KflwaZ+8QRcKSqYL49kTh11VD5iomJ0cixwQS0qpybQGE68zE:koJ3RiFZyRre4oPVD52J0cFZ0qsbXpIE",
            "96:vr71FxOn3v33oc4oRhlHMEwN4Pak8Q2G5oPKs9tIhe5A2E51asJlXaxithi:vrVOn3voHorOv6ak8/Ss9t8km5MsvzO",
            "48:uLdO3cVM2fnh2XGkj1NA97/Uvek/CPwOAzPi/UX93g9RXoVPm1tpGrDDv1Jkd0SM:u5Ks2XG+Q9TDkJi/UX92b1e/PkWB",
            "384:hjRVANfvAEyrA6X870M/cD+ugHg4lSKCqWP9ODq9wkPEAjzvNdPUq4Onie3MT8q:5uAEiA6X87HDpHlSMCOu9lcAnh3e",
            "96:6aZEatA2AwF4FQF7F60F6GzyxyIMO9qbNRNRFgdCRdCRdCR6cgz+000tk+:JhA2Aw2e9000GzyxyIMO9qRLDg8R8R8o",
            "24:oVX+85U/Fs5raJqnX5Hjpys9EcSUEiCyqWTrbFJeWWpX60MO:q+BF6rTpjpjEcSUEpyXbFJeDpXfMO",
            "192:bEkwdaiD1OqtCq1otracGyhUNE5x+qEDtCKP15:bwZ1OCT1MracGuVL/EDl95",
            "384:fyESMQf4G3OR+3Y+TwjydYDZlrzjenuUG8vTqwp0:KjaR+gjKY1lzeu58Y",
            "24:sTqKV8rFZ5pgByGEJYblLLadOrlw8DZ5DfQAhXoFkjyB0TdRkjJhjpkL:fTpg6JYta+Nd5JBoOG+J6iL",
            "192:BU2t8+CRba+Mxw1+BXiw+Cyy3IGRqh72jwrE+JrAo1N0h:Hu9JHMxw1+Byw+ly3RA72sIGJ1NE",
            "24:eGZF6hlZ2tkt/HyATR06WjdQduEAa5yFdj29EWPReW6nySF3if9zp1F9YB27Ky02:36hsC/nRHuerAbj29EyDMOp1Ll63HkYI",
            "96:s9i1VJGOGH8fV1JcmR0NQRoUmzeo/rUGdVLeOm1jnFDBduj4wJ9MdSs:z71pR0aRoTzeUxVLeOWFD37wJ9Mdf",
            "96:VPvzDgIT7I7WX403MsH1YqKH33w2KH53wZzXPKH53P8Gwa:VPfgwI7WXMswH33wNH53wcH53z",
            "384:5IaBH/vBI+0uZ553GqBEZif4+l5c2eMSEq4Y9DDu/YAdyYhcyUCRxxkZ9jI0JQr2:iaIxYi08h3J4zdf0CRxxwZI0erdaDoo7",
            "192:OkHXDLXwKMeUXYgE0f7+BG7vJ2CgZs3N8cMtJpbQmg7IKvm5xFi7yg35FsJ9u:Oy/XwKdUog/+c18yqhtUm6IKvm5xFI1t",
            "192:S9D+aG5vLlyP9FIIcaHvOi8aQoUnp7h7n2F0BVUfWXgo/HN8y0m2uv4+s:S9y3DlyvhP2hbGcvRs",
            "96:YSe21XbR5oGw3YsDS0U1KI3Hj6bZQxYbAv9zWuWpN9ZvS:YSe21L0Gw3jS0U1d3HIS+bAvtWLpN90",
            "48:YrZKSnv38q8QQsTV/EuxPGRfW2+v58bEYvu8BQy+WebYbAvb9HyBW6xWFbmQ3dUc:YrRnv3x8QQIEux+Fj+CbyQQxYbAvxmWF",
            "48:kQ61jtJVyvh60dLaJG+N7+NmFGg+JU4HDY5nWLkKqnYNgWX66FSkQ:kl1Av00peG+YmfuaqkpYNesQ",
            "96:w7rHTeMZZzUHm+ULbua1Rp3SFNrfI/BHFGtqd:w7rqMjzUE+0RRC5wFkQd",
            "96:AvVAnIxR8AvWCyT6LL1Rdx29poitqJ/+c23jMwUBBpMcE:e2nI1yTqJeK3yMwUBBpxE",
            "192:8XeT735jqDmB134NJOD+uRAxIA9aYSKGcr/5tDK0:8XevJjJB1324D+uRzAAPKGcr/bK0",
            "96:58vkp/fXkk78x/GWxr5z7E4SImLzW5d/gDbacUeU1e+Tz6jft/ITKpZUNvSTtTrd:53/R8YWx5SImRpUzn0ft+iRCT+3",
            "192:YbDynvyjdMpbzGe2zBldPHuamjtJoTLg+tOvnoKT1BKbZNVudhTyTg0g:YbGnvyipbzsBlZHZ4J2gYSnoKT1BiGhV",
            "384:bjCn/IhVgx/JL22AU1e5jjcbk4C0fmBReFiXDL:bju/IhVaC2AaeljMk4CbBRNL",
            "96:QOU9WIH99lsUhwDiffVJheNZPg0GJBE6D2tFi4/9ZTe+c0:K9WIflphpJsLg0auWAi4/91ei",
            "192:y9oZSjTADbZGjpqG76FXmxd7DZsLYou78J/rAk1RSIucIa9p1Isvk:yygj0HZOqG76FI7DZsLFukMk4cIa9guk",
            "192:3WCtVjvicl2Znn88qaaMBX1icdguiFaDhd:GC/qu2R8hvcdgktd", "96:89aOB8pXPkkOgtWD6yrLODd1VUOC4A6YCFdWJMbJKzqo862ojOLLqaLOe1LXXS65:89EQLOvV9r/CZGo862oCLL3LOe1LZD",
            "384:14CuBPJXS22fZ/I9F93QG4921c/HeHNLY14YkS6yE:ShJXXbc/+HckS6Z",
            "96:jFfYNrNeEfO8IJaRSH/9qEIO0ic6jSdaHTgTC3ZC5wFFKUuq4Cxba7YBdgkQgQnq:juNrNbO8Oa0I6jSuTycU5wxXHx2fi0bi",
            "192:5+uwhV7Bvc+i8lrKLqHG6KkRV0+/ERj9imV:52hd2XOTHG6KkT0+/cV",
            "96:2EEXCptETx5OO3U3VYFyQraIyI1yM1kvppmPkihb+cjirKm51g:BEy7EN5KY9a81yM1kvKPP2rKm51g",
            "384:+RmMKgmL7zOS4NeYrv76Z+/7BEEvCaiw0S374+yo:+4MKtLvOOYa+/bvC2cLo",
            "48:RulOqc96nxX0TmhYqYZ+fziwgm1ooskbI+fBjBOMELhnQMM5d8nQ19MUR82zPKxG:QbznRM3+XjpvISMM5d8e9Vq2zcir8CVV",
            "192:8xNtwg/IeP3ViGvIN2HAqgv11KuClN83YmQx4cbaRbkuw0l/mGk9q+:UNtxPPm2gu18omQKceRwun/mQ+",
            "384:RfRT3DzrUvar8H/JS0fyVI4sHkrwzBskoFlgManl8iiMO:RfR73ASIH/vya4s3NjO",
            "192:9kJD+3shQkY4DlZQbchMe2vsDRTqPxE3N+Vc9LDBoVEOFsOD+RKpbvOzMI6Af:9EDMshLxZQwhMnvsFmecc9PrIRDaKz2f",
            "96:+E/uPXXFcjbPa2lH/yvwUp4JkJ3tZdVKpmisbIfNfPWp:QX5OH/DawmiwyNfPi",
            "192:9FyrmH0UYzErwSG464txxxSg+aug4GNA8hYkz1vUN4o:9FyrQ0UqCw4xxqa7VC86kz1vgn",
            "96:8vFvrtDtKEhxXznKKdvDxa82W3BYoS4hRszqB5+l87TPi6UnodLPm2BGsE:6vBDtKELnKKdVaBmBFR2qB5+l87TPind",
            "384:7o+EaukNAPcMUf5RTnJzFtZR2IlM/Y36KDIJXslRRs3U9+90uYHtZzcO3:70aukuFk57JvRBlS0ss+oTb",
            "384:QdDRti6cVj6QQxKn5d3cQZl0DKPC7b0U2n6kZbXxKzoL5fX:gyV9pMhs6kJx3Lh",
            "96:HuV6+S8c4NkoJCBlJmhdkbKqCgm+QKiV9ijZSOFy+nMSwgdU30bf1TM870JQ:HdMcoulJWkKqCgHijidSOFYSw2U2x",
            "96:ZssSOIA4R+8TI8KUkGEjxWjg/y7DKWOsuiEHl/NYu2/QCottTW+SgFn:ZsQIA4oMEjxugY+WEis7YuFfaeZ",
            "192:zPulXHnEReFjz2SgvYJ4cy6tMWUT35GQVi8oQeVvKf6:zPuNwEi0G01oeZKf6",
            "48:QNGX66Pu8Ebghg0r/yr0rvtcH87o+5Ru2UhwhOlD0IG3UvM5E45LC:QIdOMb+orvtcH87x45whOFxhvI8",
            "384:OKYF0ttlnzzoF5Q+W5/tuhTmIo5GO/tRvDIVQ:OKO0ttlzzoXhGtuhTmiO/LDOQ",
            "384:fp2nNP3HesL8ac0GlytJor0Ql3O/jBxjIFL3L:fpSPXGaSJwQQTkFf",
            "192:0B6dAx/St/Hs0HX7AJL4yF2QAsD9MUDDQ5WUUfjMLtomWLzQC:88Ax6tPseyL4yoQAsD9MUHkWXbMLtom2",
            "96:GBErvouBJmbq4cA4KfTO3pt5vNh/YmjYqTDp4m8ltnPyLK03xoG:P1YGetLOFvHQm0qTDp67PymOxr",
            "192:8NU98L7C4ftZZGtha4rEn4dN7k44WZEx2kaxZ18V8YLze:cU9871/i2cnWixZ1o88q",
            "96:tkz/9+YpogYCzPYq1e/T2Ppcc1FNsJYBt9+QB0iBt9xJMt2:yFXYCD5k/T2PpcIni4b+QB/Bt9xu8",
            "96:5sakGryMxuFui3cyQhQuKPnio7Fv9Gr/Oj5vpABMuot:6a3WMIFuiIeKOFvI/Oj5Bgot",
            "384:eVwggQ2BJXTO329k0ykz3AqMjg8OJFRK4sIaNqX65TJAhRZW8:eCzTGyk0P3EqCNA65TmT/",
            "96:gN8YXCdyzrLn9XO4Lo2ycsF/ylUmydRcl3YPagBZ+O/:B/y/L82y5yl7y63YPaYZ+O/",
            "192:5g0AZF1XFbQRlZ5zI1rl8RcvX3pSDZxLojADhLo5tJNc:5K1dQRlZ5zUKRKXcDZxsQhkc",
            "192:nuQTeTOsXZq5zgoE3JGDg8fXg1+Sr9JB6k:nuQmOspq5zU3JGDgyXg7r976k",
            "96:6gzeNkItru/cc+H4NyTGDNivDnzsA6PHmFmZeG0PDV8qP1cTb2XLCRom:6fxru/wPvDzEHmUZROhLPSTuqV",
            "384:vz4uNBihHollE7SbpiYwz7CKZIbmdS+R9BwgxtZBZri544Nmcc4bKswdjeXsKxAA:r4KfkavIPfRZt1rrccIKHhO",
            "96:YLtaCwK3iywHzn5hI5GOBRHYiz8D3Qcef4k4A:cK/rzn5hI5nR4i23Q5fb4A",
            "48:Qp/yo40j/2ttQl6E400GT9jTGciih0TcKyWDJL0iZvb3Wxbb:QVl/2jiRGGTdTGcii8tL0V3",
            "3:+NPBuXbCKs4UUEF6ogwvcsDPvn:+N5WtxUUEF69wEiX", "3:PqcHrIwcHALW7pAsd4MKLLHmv:PLIwkGMKPY",
            "384:mxO21Gim/Yf5G3t3PkEbx+RAmzUyzJhFGl3fvzFUadyKK6dla8H:j21GBQA3t3PrRZr",
            "48:jSf/G1QyVVnyfoq85hwZ9BiR7X6BY2eWeUWwOyeQPCwCEOQ4XDS:jS3UIfuwZ9ol6BY2ewWwyQPCw/P4Xm",
            "96:QbwUbdjA76KAXuUdRME2ZEfOHMwp2jzM6RQRUB3IP7ES:QEUJje6fzd6Zs+MMSfRQRo3ITN",
            "192:+BlTxMhSjJt+8nJI3NvM/wiVotRNvM1xDzjHoRD1wNdNtVl9ApR2NRrJXx76sZ1S:OMhSjJc3NAGvM1xTmDSBl9AOPf7H+h",
            "192:c413I/Sv+dXB6DICZf9Wmay470BEAo2EApNed9PJaAR4OZtZ1RR40HmJm7kqKgNJ:BZ2dYEIlra54abPJa1kDRrHugv",
            "384:4YDra4puXCUnXWKbA1spuVJoUgfjQH5I1jWzeUcVc:4YDdpuXVnq1PqjHjKMVc",
            "96:mtDCIG/QiLwk4NfpW+1Dwg77M+t5M8zF4upFkOTU+AqxKejKu0QwgYKvm6:jIIQU4vsKM+s8G7Oo+8ejKu0L5Ix",
            "96:ClGYVRFnyemYkElpxe/rbEbXbNOsTndZxuR1WvLTd6ysA7X9AS7moCDa/jBpWZOH:qGKPnb8E38WLEWdHVPX9AS/CaputS",
            "384:SnaOlbgnLNCl+e69Mgf/zkiDDS3ynhhoWPLTkNMEZ9jS1MQ/YqkwQdPmJYHC:XKqCl+f/zyGhnXT2QgdwZ",
            "192:LffDfA0hI8iHH7hvc9LoitnjtEkFSn7gOY:nDXiHH7hvPmnlQ7RY", "96:alV+4+h8QF2RQjBhroM63yepIQWl2/tVVgwqxgulLidoFZoewmGxjVU4vwF73ABX:auL4RrpIQMiNgwq6ulLidoFZoewjpVBX",
            "192:/D4a5I/qlHBCR3TT07A+NxcJ3a1oqoPrvYJ+XyjxFDgsxeuJHIW3:/D4yI68RfKA+NC3a1Ta0+XyjxRVeiHI4",
            "192:e4fjiTFth8VaNuVvvfwK1Bd/uYjyl2A/lvW2mihDOiBWi0MZeB:e2aUVvvbBIYc2A/3mihDOV5j",
            "192:oTozcDixKfY2sQezskBfL26kHypftY9rs+jzvBLR1g/PF8hD6H0SpSWcYByYl:oecDemYQezVapHypf4b/vv16UjKJl",
            "96:8da37Dlel/pxBaaKmjIdfO1GMf/L9YfSvKZl7tT2Kq0OL7NPG5vEDpU3JIQD71XE:8sSLaahjId266iZX2LtXNPGFwUZiSbPa"
)), row.names = c(NA, -80L), class = c("tbl_df", "tbl", "data.frame"
)) -> orig

list.files(
  system.file("extdat", "baseline", package = "ssdeepr"),
  full.names = TRUE
) %>%
  hash_file() -> now

expect_true(all(now$hash == orig$hash))

expect_true(hash_compare(now$hash[20], orig$hash[20]) == 100)




