# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Test whether an object is an external pointer
#'
#' @param x object to test
#' @keywords internal
check_is_xptr <- function(s) {
    invisible(.Call(`_ssdeepr_check_is_xptr`, s))
}

#' Test whether an external pointer is null
#'
#' @param x object to test
#' @keywords internal
is_null_xptr_ <- function(s) {
    .Call(`_ssdeepr_is_null_xptr_`, s)
}

int_fuzzy_context <- function() {
    .Call(`_ssdeepr_int_fuzzy_context`)
}

int_fuzzy_update <- function(sctx, v) {
    .Call(`_ssdeepr_int_fuzzy_update`, sctx, v)
}

int_fuzzy_digest <- function(sctx) {
    .Call(`_ssdeepr_int_fuzzy_digest`, sctx)
}

int_hash_file <- function(path) {
    .Call(`_ssdeepr_int_hash_file`, path)
}

int_hash_buf <- function(v) {
    .Call(`_ssdeepr_int_hash_buf`, v)
}

int_hash_cmp <- function(h1, h2) {
    .Call(`_ssdeepr_int_hash_cmp`, h1, h2)
}

