# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

int_hash_file <- function(path) {
    .Call(`_ssdeepr_int_hash_file`, path)
}

int_hash_buf <- function(v) {
    .Call(`_ssdeepr_int_hash_buf`, v)
}

int_hash_cmp <- function(h1, h2) {
    .Call(`_ssdeepr_int_hash_cmp`, h1, h2)
}

